# Generated by Django 3.2.7 on 2022-01-21 15:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='task',
            options={'ordering': ['created']},
        ),
        migrations.RemoveField(
            model_name='task',
            name='complete',
        ),
    ]
